-- while game:GetService("RunService").RenderStepped:wait() 
-- do
-- local A_1 = "VampireBurn"
-- local Event = game:GetService("Workspace").Living.bowjvaleriy.RemoteEvent
-- Event:FireServer(A_1)

-- end


 
-- local A_1 = "UpdateState"
-- local A_2 = Enum.HumanoidStateType.Jumping
-- local Event = game:GetService("Workspace").Living.bowjvaleriy.RemoteEvent
-- Event:FireServer(A_1, A_2)


 
-- while game:GetService("RunService").RenderStepped:wait() 
-- do
-- local A_1 = "VampireBurn"
-- local Event = game:GetService("Workspace").Living.bowjvaleriy.RemoteEvent
-- Event:FireServer(A_1)

-- end

-- while game:GetService("RunService").RenderStepped:wait() 
-- do
	
-- 	local A_1 = "ToggleSprinting"
-- 	local Event = game:GetService("Workspace").Living.bowjvwaleriy.RemoteFunction
-- 	Event:InvokeServer(A_1)
-- end


-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
a = 0
-- .StandMorph
print("STARTED")
while game:GetService("RunService").RenderStepped:wait() do
    a = a + 1
    game:GetService("Workspace").Living.fartunatuna:WaitForChild("StandMorph")
        for i,v in pairs(game:GetService("Workspace").Living.fartunatuna.StandMorph:GetDescendants()) do
            if v.Name == "Hierophant Green Stand Barrage" then
                v:Destroy()
            end
            if v.Name == "PilotSpeed" then
                v.Value = 5
            end
            if v.Name == "IsPiloting" then
                v.Value = 179.49999999999997
            end
        end
    game:GetService("Workspace").Living.fartunatuna.HumanoidRootPart.StandAttach.CFrame = CFrame.new(0, 0, 0)
    game:GetService("Workspace").Living.fartunatuna.HumanoidRootPart.CFrame = game:GetService("Workspace").Living.fartunatuna.StandMorph.HumanoidRootPart.CFrame
    game.Workspace.Gravity = 0
    if a > 4000 then
        print("BREAKED")
        break
    end
end